version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "sqlite:///db/database.db"
    restart: unless-stopped
    command: ["python", "run.py"]
